version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Downloading Flyway CLI..."
      - curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.11.0/flyway-commandline-10.11.0-linux-x64.tar.gz | tar xz
      - mv flyway-*/flyway /usr/local/bin/flyway
      - chmod +x /usr/local/bin/flyway
      - echo "Flyway installed at: $(which flyway)"
      - echo "Flyway CLI installed successfully"

  pre_build:
    commands:
      - echo "Flyway version:"
      - flyway -v
      - echo "Current directory:"
      - pwd
      - echo "List sql files:"
      - ls -R sql
      - echo "Running migration..."
      - flyway -configFiles=flyway.conf migrate

  build:
    commands:
      - echo "No build needed – migration only"

artifacts:
  files:
    - '**/*'
