version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Downloading Flyway CLI..."
      - curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.11.0/flyway-commandline-10.11.0-linux-x64.tar.gz -o flyway.tar.gz
      - tar -xzf flyway.tar.gz
      - mv flyway-10.11.0 /opt/flyway
      - ln -s /opt/flyway/flyway /usr/local/bin/flyway
      - chmod +x /usr/local/bin/flyway

  pre_build:
    commands:
      - echo "Fetching parameters..."
      - DB_HOST=$(aws ssm get-parameter --name "/Prd/online/spring.datasource.endpoint" --query "Parameter.Value" --output text)
      - DB_PORT=$(aws ssm get-parameter --name "/Prd/online/spring.datasource.port" --query "Parameter.Value" --output text)
      - DB_SCHEMA=$(aws ssm get-parameter --name "/Prd/online/spring.datasource.schema" --query "Parameter.Value" --output text)
      - DB_USER=$(aws ssm get-parameter --name "/Prd/online/spring.datasource.username" --query "Parameter.Value" --output text)
      - DB_PASSWORD=$(aws ssm get-parameter --name "/Prd/online/spring.datasource.password" --with-decryption --query "Parameter.Value" --output text)

      # Compose JDBC URL
      - FLYWAY_URL="jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}"

      - echo "Writing flyway.conf..."
      - echo "flyway.url=$FLYWAY_URL" > flyway.conf
      - echo "flyway.user=$DB_USER" >> flyway.conf
      - echo "flyway.password=$DB_PASSWORD" >> flyway.conf

      - echo "Running Flyway migration..."
      - flyway -configFiles=flyway.conf migrate

  build:
    commands:
      - echo "No build needed – migration only"

artifacts:
  files:
    - '**/*'
